FROM rust:1.90-bookworm

RUN rustup component add rustfmt clippy

RUN apt-get update \
    && apt-get install --yes --no-install-recommends zsh \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY . .
