name: Tests

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@b85815f71a6de0ddee80b8a80a98d43f4bcc66c7 # v31
      - name: Format, test and lint
        run: |
          nix develop ./.nix --command sh -euc '
            cargo fmt --all -- --check
            cargo test --locked
            cargo test --manifest-path vendor/vt100/Cargo.toml --locked --lib
            cargo clippy --locked --all-targets -- -D warnings
            cargo fmt --manifest-path vendor/vt100/Cargo.toml -- --check
            cargo clippy --manifest-path vendor/vt100/Cargo.toml --locked --all-targets -- -D warnings
          '
